language: java
sudo: false
install: true

addons:
  sonarcloud:
    token:
      secure: "IzVD4xEBOYM2jEdbiE2GinK0GThNI6Yz/RbgKL01pzH4tqJNSqOQzLyXygneg5/2CG2QqENimt51hxGVjNSqMXnrbQ315n7zB8yszN27aUpAUlAJIULlK0Aox1kNG1yyva6/g8HVdce2eFyh73rYDbEx/ReVqIcOk4IPPxYPIS6m3KYN2lcuI3RsImTbrzylO/0UdzheVO53v1KTpRdUjL0cSakN4HTBQ1m2tlRYP8YLDqhR01M1iSYLrcQUmRbQtfVxzF+GD3TpWLK9aq6UbKkwfLnzxEyTrwaktsm5VNMYAbAJ+L5LIdypffzDMO1iJXpn6A96NZq9t0ggiEq2ZWpyTd+JHTFCCo7AlwvBlnauLSZAmTpoU1xzwvc1mgm8Prg2d1CRt8fIdmm07BAgatmKIabezBVl3xTyz7WLB0Dzn1sfh4RKkKNRvOamvCOhT2xFn595oGshXXLE8mmrVarCmJUW7CqbrMqXslSszsbG/h7i7ukIDFKDgfJubGqRdtOtDug4Lksm7a83WNq9UxfXEkxFxpUm7IKRBUwCY/NG48o2M7NX43pszgjhRp5+A/c9L+UjaoZ1/bBAssqhhwD43SW0PZCGlyTYPqg5hW5VXWMuqmOxik+6b4zLa5qzz4YO49NANmjAiENP+ue+iVpxneTwQxDu83MWYpx8Fas="

jdk:
- oraclejdk8

notifications:
  email:
    recipients:
    - bdsoss@blackducksoftware.com

script:
- "./gradlew clean build jacocoTestReport coveralls sonarqube"

after_success:
- bash <(curl -s https://copilot.blackducksoftware.com/ci/travis/scripts/upload)

cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
  - "$HOME/.gradle"
  - ".gradle"
